name: CI
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            vcpkgCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
            preset: 'windows'
          - os: ubuntu-22.04
            vcpkgCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
            preset: 'unix'
          - os: macos-12
            vcpkgCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
            preset: 'unix'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set C++/C compiler on macOs
        shell: bash
        run: echo "CC=gcc-11" >> $GITHUB_ENV; echo "CXX=g++-11" >> $GITHUB_ENV; cat "$GITHUB_ENV"
        if: runner.os == 'macOs'

      - uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: ${{ matrix.vcpkgCommitId }}
          cache: false

      - name: GCC version on Linux
        shell: bash
        run: g++ --version
        if: runner.os == 'Linux'

      - name: Run CMake with manifest mode vcpkg
        shell: bash
        run: cmake --preset=${{ matrix.preset }} -B build -DCppSdl2_Test=1 -DCppSdl2_Example=1 -DCMAKE_VERBOSE_MAKEFILE=1

      - name: Print log message on macOs
        shell: bash
        run: cat /Users/runner/work/CppSdl2/CppSdl2/vcpkg/buildtrees/sdl2/install-x64-osx-dbg-out.log
        if: runner.os == 'macOs'

      - name: Compile binaries
        shell: bash
        run: cmake --build build
